### ISSUE TITLE
About download the models

### ISSUE THREAD

**Issue by tuji-sjp** [dongyp13/Non-Targeted-Adversarial-Attacks#10]
Maybe you could provide download links for these models?
I only found some of them on the official website [https://github.com/tensorflow/models/tree/master/research/slim](url).
Especially those adversarial models. Thank you very much!

  --checkpoint_path_inception_v3=inception_v3.ckpt \
  --checkpoint_path_adv_inception_v3=adv_inception_v3_rename.ckpt \
  --checkpoint_path_ens3_adv_inception_v3=ens3_adv_inception_v3_rename.ckpt \
  --checkpoint_path_ens4_adv_inception_v3=ens4_adv_inception_v3_rename.ckpt \
  --checkpoint_path_inception_v4=inception_v4.ckpt \
  --checkpoint_path_inception_resnet_v2=inception_resnet_v2_2016_08_30.ckpt \
  --checkpoint_path_ens_adv_inception_resnet_v2=ens_adv_inception_resnet_v2_rename.ckpt \
  --checkpoint_path_resnet=resnet_v2_101.ckpt \

**Comment by dongyp13** [comment]
The models can be downloaded [here](http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip)

**Comment by tuji-sjp** [comment]
Oh, thanks!!
