### ISSUE TITLE
Some problems about code and paper

### ISSUE THREAD

**Issue by Amarantine1** [dongyp13/Non-Targeted-Adversarial-Attacks#16]
@dongyp13 Hello, excuse me. Is  attack_iter.py the code of the integrated countermeasure sample algorithm in this paper? I'm not sure, it seems to be integrated code. If so, where is the algorithm code for single model to generate counter samples in this paper? Do I need to write it myself or how to operate it to become a single model attack algorithm? There are a lot of questions. Please forgive me. I'm a novice. thank you

**Comment by dongyp13** [comment]
We attack the ensemble of 8 models in attack_iter.py. If you want to attack a single model, you need to modify the model definition part. The [attack code](https://github.com/dongyp13/Non-Targeted-Adversarial-Attacks/blob/5c68162e05de7afed2e3d33115df43e2a7a1c3da/attack_iter.py#L176-L190) can be reused.
