### ISSUE TITLE
some problems about the code

### ISSUE THREAD

**Issue by xiaomiu311621** [dongyp13/Non-Targeted-Adversarial-Attacks#17]
Excuse me. I have ran the code attack_iter.py but I got an error like that " topological sort failed with message:The graph couldn't be sorted in topological order".Can you give me some advice?Looking forward to your reply.Thank you very much!

**Comment by dongyp13** [comment]
You may try lower versions of Tensorflow, e.g., 1.1.0.

**Comment by xiaomiu311621** [comment]
Thank you very much.I will try again.
