### ISSUE TITLE
a confusion

### ISSUE THREAD

**Issue by YeEmrick** [dongyp13/Non-Targeted-Adversarial-Attacks#2]
Hello,
there is my confusion  at graph() method in attack_iter.py file:
`first_round = tf.cast(tf.equal(i, 0), tf.int64)`
`y = first_round * pred + (1 - first_round) * y`
`one_hot = tf.one_hot(y, num_classes)`
it's means that we calculate cross_entry between pred and logists at the first iteration and the remaining iterations are between y and logists?why are you calculate cross_entry between pred and logists at the first iteration specially? the paper's Algorithm 1 seems not show these details.
thank you

**Comment by dongyp13** [comment]
Hi, we use the prediction of the raw image as label to generate adversarial examples. So in the first iteration, we use pred to calculate cross entropy and store pred to y for later iterations.

**Comment by YeEmrick** [comment]
Oh, I see, thank you!
