### ISSUE TITLE
run attack_iter.py

### ISSUE THREAD

**Issue by gmt710** [dongyp13/Non-Targeted-Adversarial-Attacks#3]
run attack_iter.py and get an error like that " UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte ".

**Comment by dongyp13** [comment]
Does the error occur when loading images? Please make sure that your images can be loaded by scipy.misc.imread.

**Comment by qilong-zhang** [comment]
@gmt710 
Hi!
Have you solved it? I meet the same error?

**Comment by forwardwfg** [comment]
@gmt710
Hi!
Have you solved it? I meet the same error.

**Comment by gmt710** [comment]
@WeifaGan ,hello.
I vaguely remember that it might be the scipy version that caused this problem.

**Comment by Amarantine1** [comment]
Hello, your method is very good. I am repeating your method recently. I'm a novice. I don't understand many problems. 1. I'd like to ask V3, V4 and other models to train and save with your code (such as V3_ test.py Training is not successful), or download it on the official website? 2. About attack_ iter.py File directory configuration problems in, such as checkpoint_ path_ ens3_ adv_ inception_ How to initialize the path of V3?Sorry, there are a lot of questions. I hope to understand. I'd like to reproduce your methods to help my research. If possible, I can send QQ email -228297179@qq.com , you can reply and view at any time, thanks

**Comment by Amarantine1** [comment]
> run attack_iter.py and get an error like that " UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte ".

Hello, are you still studying this field? How is your reproduction of the author's method?

**Comment by gmt710** [comment]
Well, I have graduated, but I will focus on this field. I'm a little busy, so I don't have to devote a lot of energy to studying Adversarial examples as before.

**Comment by gmt710** [comment]
This code is not hard to run.If you have more questions, you can solve them.If you're new, I suggest you take a look at foolbox. Then run a little demo of the MNIST dataset.

**Comment by Amarantine1** [comment]
> Well, I have graduated, but I will focus on this field. I'm a little busy, so I don't have to devote a lot of energy to studying Adversarial examples as before.



> This code is not hard to run.If you have more questions, you can solve them.If you're new, I suggest you take a look at foolbox. Then run a little demo of the MNIST dataset.

Oh, congratulations on graduation. I just entered school. The teacher arranged to study this direction and asked me to run the author's code as soon as possible. Now I have downloaded the dataset. But there are many models in the article, I don't have them. So attack_ iter.py Unable to run. How can I solve it? (you can reply slowly if you are busy) thank you

**Comment by gmt710** [comment]
Thanks.
What problem do you have met?May You be able to search on your website.

**Comment by Amarantine1** [comment]
> @gmt710
> Hi!
> Have you solved it? I meet the same error.

Hi, have you finally solved it? I have a few questions for you. Do you have time?

**Comment by dongyp13** [comment]
Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.

**Comment by Amarantine1** [comment]
> Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.

Hello, thank you for your reply. The previous problem has been solved. Now there is a question about the role of files under nets in the project (such as inception_ V1_ test.py , it doesn't seem to be used to test against images, so what's its purpose?

**Comment by dongyp13** [comment]
> > Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.
> 
> Hello, thank you for your reply. The previous problem has been solved. Now there is a question about the role of files under nets in the project (such as inception_ V1_ test.py , it doesn't seem to be used to test against images, so what's its purpose?

Right. There is no need to keep such files. We just copy the `nets` folder from [https://github.com/tensorflow/models/tree/master/research/slim](https://github.com/tensorflow/models/tree/master/research/slim).

**Comment by Amarantine1** [comment]
> > > Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.
> > 
> > 
> > Hello, thank you for your reply. The previous problem has been solved. Now there is a question about the role of files under nets in the project (such as inception_ V1_ test.py , it doesn't seem to be used to test against images, so what's its purpose?
> 
> Right. There is no need to keep such files. We just copy the `nets` folder from https://github.com/tensorflow/models/tree/master/research/slim.

Thank you. How can I solve this problem：(Here is the problem code)

 for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
    with tf.gfile.Open(filepath) as f:
      image = imread(f, mode='RGB').astype(np.float) / 255.0    (The picture cannot be read correctly here，The error is ：'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte)
    # Images for inception classifier are normalized to be in [-1, 1] interval.
    images[idx, :, :, :] = image * 2.0 - 1.0
    filenames.append(os.path.basename(filepath))

I have looked at many materials and tried to modify them, but none of them have been solved.What should I do? Can you help me? Thank you very much

**Comment by dongyp13** [comment]
> > > > Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.
> > > 
> > > 
> > > Hello, thank you for your reply. The previous problem has been solved. Now there is a question about the role of files under nets in the project (such as inception_ V1_ test.py , it doesn't seem to be used to test against images, so what's its purpose?
> > 
> > 
> > Right. There is no need to keep such files. We just copy the `nets` folder from https://github.com/tensorflow/models/tree/master/research/slim.
> 
> Thank you. How can I solve this problem：(Here is the problem code)
> 
> for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
> with tf.gfile.Open(filepath) as f:
> image = imread(f, mode='RGB').astype(np.float) / 255.0 (The picture cannot be read correctly here，The error is ：'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte)
> # Images for inception classifier are normalized to be in [-1, 1] interval.
> images[idx, :, :, :] = image * 2.0 - 1.0
> filenames.append(os.path.basename(filepath))
> 
> I have looked at many materials and tried to modify them, but none of them have been solved.What should I do? Can you help me? Thank you very much

I think it's due to the scipy version. You can try to use early versions of scipy, such as v1.2. Or you can try to use other image loading functions, such as cv2.

**Comment by Amarantine1** [comment]
> > > > > Hi, sorry to reply late. This code is used to attack pre-trained models. So you don't need to train those models. We have provided a link to those models. You can also download them at the official repo.
> > > > 
> > > > 
> > > > Hello, thank you for your reply. The previous problem has been solved. Now there is a question about the role of files under nets in the project (such as inception_ V1_ test.py , it doesn't seem to be used to test against images, so what's its purpose?
> > > 
> > > 
> > > Right. There is no need to keep such files. We just copy the `nets` folder from https://github.com/tensorflow/models/tree/master/research/slim.
> > 
> > 
> > Thank you. How can I solve this problem：(Here is the problem code)
> > for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
> > with tf.gfile.Open(filepath) as f:
> > image = imread(f, mode='RGB').astype(np.float) / 255.0 (The picture cannot be read correctly here，The error is ：'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte)
> > # Images for inception classifier are normalized to be in [-1, 1] interval.
> > images[idx, :, :, :] = image * 2.0 - 1.0
> > filenames.append(os.path.basename(filepath))
> > I have looked at many materials and tried to modify them, but none of them have been solved.What should I do? Can you help me? Thank you very much
> 
> I think it's due to the scipy version. You can try to use early versions of scipy, such as v1.2. Or you can try to use other image loading functions, such as cv2.

Hello,"filepath" already refers to a specific picture, but here (with... As) is also used, resulting in imread () can not read the picture successfully, so the (with... As) line of code should be deleted, so it can work normally.
code：for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
                with tf.gfile.Open(filepath) as f:    (should be deleted)
                image = imread(f, mode='RGB').astype(np.float) / 255.0  (replace   it with  image = imread(filepath).astype(np.float) / 255.0)
