### ISSUE TITLE
Zebra Class Failure Case

### ISSUE THREAD

**Issue by MohammedAbdou285** [dongyp13/Non-Targeted-Adversarial-Attacks#5]
Hello,

I have tried the algorithm on Zebra Class of ImageNet. However, it fails in doing adversarial attack which means the whole models predicts the Noisy image as Zebra as well.

Is this case normal ? Have you checked all ImagNet Classes ?

Thanks

**Comment by dongyp13** [comment]
Hi,

We didn't check the misclassified labels of the adversarial examples. It's true that DNNs may be fooled by some noisy patterns (See the paper "Deep Neural Networks are Easily Fooled").
